{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "live-epg.fullname" . }}
  labels:
    {{- include "live-epg.labels" . | nindent 4 }}
spec:
  host:  {{ include "live-epg.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: {{ .Values.istio.destinationRule.loadBalancer }}
{{ end }}