{{ if .Values.externalServices.enabled }}
{{ $dot := . }}
{{  range .Values.externalServices.svc }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "live-epg.fullname" $dot }}-{{ .name }}-service
  labels:
    {{- include "live-epg.labels" $dot | nindent 4 }}
spec:
  ports:
  - port: {{ .servicePort | default 80 }}
    name: {{.type }}-{{ include "live-epg.fullname" $dot }}-{{ .name }}-service
    targetPort: {{ .targetPort}}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "live-epg.fullname" $dot }}-{{ .name }}-service
  labels:
    {{- include "live-epg.labels" $dot | nindent 4 }}
subsets:
    - addresses:
      - ip: {{ .ipAddr }}
      ports:
      - port: {{ .targetPort }}
        name: {{.type }}-{{ include "live-epg.fullname" $dot }}-{{ .name }}-service

{{ end }}
{{ end }}
