apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for Kubernetes
name: live-epg
type: application
version: 0.1.0
dependencies:
- name: mariadb
  version: 13.1.3
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
