# Default values for live-commenting.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.aban.io/live-epg
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "COMMIT_SHA"

app:
  env:
    enabled: true
    data:
      PORT: "8080"
      MS_NAME: live-epg
      SERVICE_NAME: live-epg

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

istio:
  enabled: false
  virtualService:
    host: live-epg.<NAMESPACE>.svc.cluster.local
    port: 80
    type: http
    urlPrefix: /
  destinationRule:
    loadBalancer: ROUND_ROBIN


externalServices:
  enabled: false
  svc:
  - name: mysql
    type: tcp
    ipAddr: 10.192.168.10
    targetPort: 3306
    servicePort: 3306



serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations:
  aban-app/type: simple
  aban-app/name: live-epg

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80



resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

mariadb:
  enabled: false
  auth:
    rootPassword: "changeme"
    database: "live_epg"
    username: "live_epg"
    password: "changeme"
    replicationUser: "repl_live_epg"
    replicationPassword: "changeme"
